
import { UserProfile } from '@/types';

const basePrestadores: UserProfile[] = [
  // LIMPEZA
  {
    id: 'mock-limpeza-1',
    auth_id: 'mock-auth-limpeza-1',
    nome: 'Maria Silva',
    email: 'maria.silva@teste.com',
    tipo: 'prestador',
    bio: 'Especialista em limpeza residencial e comercial. Cuido da sua casa com carinho e dedicação.',
    descricao_servico: 'Limpeza completa, faxina, higienização de estofados e carpetes.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Jardim Botânico',
    nota_media: 4.9,
    premium: true,
    servicos_oferecidos: ['Limpeza', 'Diarista', 'Faxina'],
    foto_url: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Limpeza' }, preco_min: 120, preco_max: 250 }] as any
  },
  {
    id: 'mock-limpeza-2',
    auth_id: 'mock-auth-limpeza-2',
    nome: 'Ana Paula Souza',
    email: 'ana.paula@teste.com',
    tipo: 'prestador',
    bio: 'Diarista experiente, pontual e detalhista. Referências disponíveis.',
    descricao_servico: 'Faxinas pesadas, limpeza pós-obra e manutenção diária.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Centro',
    nota_media: 4.7,
    premium: false,
    servicos_oferecidos: ['Limpeza', 'Diarista'],
    foto_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Diarista' }, preco_min: 100, preco_max: 180 }] as any
  },
  {
    id: 'mock-limpeza-3',
    auth_id: 'mock-auth-limpeza-3',
    nome: 'Empresa Clean Fast',
    email: 'contato@cleanfast.com',
    tipo: 'prestador',
    bio: 'Equipe especializada em limpeza corporativa e pós-obra.',
    descricao_servico: 'Limpeza de escritórios, condomínios e grandes áreas.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Setor Industrial',
    nota_media: 4.8,
    premium: true,
    servicos_oferecidos: ['Limpeza', 'Comercial'],
    foto_url: 'https://images.unsplash.com/photo-1581578731117-104f2a863a30?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Limpeza Comercial' }, preco_min: 300, preco_max: 1000 }] as any
  },

  // REPAROS & ENCANADOR
  {
    id: 'mock-reparos-1',
    auth_id: 'mock-auth-reparos-1',
    nome: 'João Encanador',
    email: 'joao.encanador@teste.com',
    tipo: 'prestador',
    bio: 'Serviços hidráulicos em geral. Vazamentos, entupimentos e instalações.',
    descricao_servico: 'Conserto de vazamentos, troca de torneiras, caça vazamentos.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Vila Rica',
    nota_media: 4.8,
    premium: true,
    servicos_oferecidos: ['Encanador', 'Hidráulica', 'Reparos'],
    foto_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Encanador' }, preco_min: 80, preco_max: 300 }] as any
  },
  {
    id: 'mock-reparos-2',
    auth_id: 'mock-auth-reparos-2',
    nome: 'Pedro Marido de Aluguel',
    email: 'pedro.reparos@teste.com',
    tipo: 'prestador',
    bio: 'Faço de tudo um pouco: elétrica básica, hidráulica, montagem de móveis.',
    descricao_servico: 'Pequenos reparos residenciais, instalações de prateleiras, cortinas.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Imperial',
    nota_media: 4.6,
    premium: false,
    servicos_oferecidos: ['Reparos', 'Montador de móveis', 'Faz tudo'],
    foto_url: 'https://images.unsplash.com/photo-1504593811423-6dd665756598?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Reparos Gerais' }, preco_min: 50, preco_max: 150 }] as any
  },
  {
    id: 'mock-reparos-3',
    auth_id: 'mock-auth-reparos-3',
    nome: 'Roberto Montagens',
    email: 'roberto.montador@teste.com',
    tipo: 'prestador',
    bio: 'Montador de móveis profissional. Desmontagem e montagem para mudanças.',
    descricao_servico: 'Montagem de guarda-roupas, armários de cozinha, painéis de TV.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Primavera',
    nota_media: 4.9,
    premium: true,
    servicos_oferecidos: ['Montador de móveis', 'Reparos'],
    foto_url: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Montagem de Móveis' }, preco_min: 70, preco_max: 200 }] as any
  },

  // ELÉTRICA
  {
    id: 'mock-eletrica-1',
    auth_id: 'mock-auth-eletrica-1',
    nome: 'Carlos Eletricista',
    email: 'carlos.eletrica@teste.com',
    tipo: 'prestador',
    bio: 'Eletricista predial e residencial. Padrão de energia e fiação nova.',
    descricao_servico: 'Instalação de ar condicionado, ventiladores, troca de fiação, quadros de distribuição.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Centro',
    nota_media: 5.0,
    premium: true,
    servicos_oferecidos: ['Eletricista', 'Elétrica'],
    foto_url: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Eletricista' }, preco_min: 100, preco_max: 500 }] as any
  },
  {
    id: 'mock-eletrica-2',
    auth_id: 'mock-auth-eletrica-2',
    nome: 'Fábio Instalações',
    email: 'fabio.instala@teste.com',
    tipo: 'prestador',
    bio: 'Pequenos reparos elétricos e instalações de luminárias.',
    descricao_servico: 'Troca de tomadas, chuveiros, luminárias de LED.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Jardim das Acácias',
    nota_media: 4.5,
    premium: false,
    servicos_oferecidos: ['Eletricista', 'Elétrica'],
    foto_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Visita Técnica' }, preco_min: 60, preco_max: 120 }] as any
  },

  // BELEZA
  {
    id: 'mock-beleza-1',
    auth_id: 'mock-auth-beleza-1',
    nome: 'Juliana Hair',
    email: 'ju.hair@teste.com',
    tipo: 'prestador',
    bio: 'Cabeleireira especialista em loiros e cortes modernos.',
    descricao_servico: 'Mechas, progressiva, cortes femininos e hidratação.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Centro',
    nota_media: 4.9,
    premium: true,
    servicos_oferecidos: ['Beleza', 'Cabeleireiro(a)', 'Cabelo'],
    foto_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Corte e Escova' }, preco_min: 80, preco_max: 300 }] as any
  },
  {
    id: 'mock-beleza-2',
    auth_id: 'mock-auth-beleza-2',
    nome: 'Amanda Makeup',
    email: 'amanda.make@teste.com',
    tipo: 'prestador',
    bio: 'Maquiadora profissional para noivas e eventos.',
    descricao_servico: 'Maquiagem social, artística e para fotografia.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Jardim Maringá',
    nota_media: 4.8,
    premium: false,
    servicos_oferecidos: ['Beleza', 'Maquiagem'],
    foto_url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Maquiagem Social' }, preco_min: 150, preco_max: 250 }] as any
  },
  {
    id: 'mock-beleza-3',
    auth_id: 'mock-auth-beleza-3',
    nome: 'Studio Nails',
    email: 'nails@teste.com',
    tipo: 'prestador',
    bio: 'Manicure e pedicure. Alongamento em fibra de vidro.',
    descricao_servico: 'Unhas decoradas, spa dos pés, esmaltação em gel.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Centro',
    nota_media: 4.7,
    premium: false,
    servicos_oferecidos: ['Beleza', 'Manicure'],
    foto_url: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Mão e Pé' }, preco_min: 50, preco_max: 120 }] as any
  },

  // CONSTRUÇÃO
  {
    id: 'mock-construcao-1',
    auth_id: 'mock-auth-construcao-1',
    nome: 'Mestre de Obras Ricardo',
    email: 'ricardo.obras@teste.com',
    tipo: 'prestador',
    bio: 'Construção do alicerce ao telhado. Equipe completa.',
    descricao_servico: 'Alvenaria, reboco, contrapiso, telhados.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Residencial Norte',
    nota_media: 4.8,
    premium: true,
    servicos_oferecidos: ['Construção', 'Pedreiro', 'Obras'],
    foto_url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Diária Pedreiro' }, preco_min: 200, preco_max: 250 }] as any
  },
  {
    id: 'mock-construcao-2',
    auth_id: 'mock-auth-construcao-2',
    nome: 'Pinturas Silva',
    email: 'silva.pintor@teste.com',
    tipo: 'prestador',
    bio: 'Pintura residencial e comercial. Texturas e grafiato.',
    descricao_servico: 'Pintura interna e externa, tratamento de infiltrações.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Jardim das Palmeiras',
    nota_media: 4.7,
    premium: false,
    servicos_oferecidos: ['Construção', 'Pintor', 'Pintura'],
    foto_url: 'https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'M² Pintura' }, preco_min: 15, preco_max: 40 }] as any
  },

  // JARDINAGEM
  {
    id: 'mock-jardinagem-1',
    auth_id: 'mock-auth-jardinagem-1',
    nome: 'Verde Vida Jardinagem',
    email: 'verdevida@teste.com',
    tipo: 'prestador',
    bio: 'Paisagismo e manutenção de jardins. Corte de grama e poda.',
    descricao_servico: 'Manutenção mensal, poda de árvores, adubação, plantio.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Jardim Itália',
    nota_media: 4.9,
    premium: true,
    servicos_oferecidos: ['Jardinagem', 'Jardineiro', 'Paisagismo'],
    foto_url: 'https://images.unsplash.com/photo-1557862921-37829c790f19?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Manutenção Jardim' }, preco_min: 100, preco_max: 300 }] as any
  },
  {
    id: 'mock-jardinagem-2',
    auth_id: 'mock-auth-jardinagem-2',
    nome: 'Sr. José Jardineiro',
    email: 'jose.jardim@teste.com',
    tipo: 'prestador',
    bio: 'Jardineiro experiente. Faço limpeza de lotes também.',
    descricao_servico: 'Corte de grama, limpeza de quintal, roçagem.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Alto da Glória',
    nota_media: 4.6,
    premium: false,
    servicos_oferecidos: ['Jardinagem', 'Jardineiro'],
    foto_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Diária Jardinagem' }, preco_min: 150, preco_max: 200 }] as any
  },

  // FRETES
  {
    id: 'mock-fretes-1',
    auth_id: 'mock-auth-fretes-1',
    nome: 'Fretes do Paulo',
    email: 'paulo.fretes@teste.com',
    tipo: 'prestador',
    bio: 'Caminhão baú 3/4. Mudanças locais e interestaduais.',
    descricao_servico: 'Mudanças residenciais, transporte de cargas, montagem inclusa.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Setor Industrial',
    nota_media: 4.8,
    premium: true,
    servicos_oferecidos: ['Fretes', 'Mudanças', 'Transporte'],
    foto_url: 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Frete Local' }, preco_min: 150, preco_max: 500 }] as any
  },
  {
    id: 'mock-fretes-2',
    auth_id: 'mock-auth-fretes-2',
    nome: 'Carreto Rápido',
    email: 'carreto@teste.com',
    tipo: 'prestador',
    bio: 'Pequenos fretes com utilitário. Agilidade e preço baixo.',
    descricao_servico: 'Entrega de encomendas, pequenas mudanças, transporte de móveis.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Centro',
    nota_media: 4.5,
    premium: false,
    servicos_oferecidos: ['Fretes', 'Carreto'],
    foto_url: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Carreto' }, preco_min: 80, preco_max: 200 }] as any
  },

  // CHAVEIRO
  {
    id: 'mock-chaveiro-1',
    auth_id: 'mock-auth-chaveiro-1',
    nome: 'Chaveiro 24h André',
    email: 'andre.chaveiro@teste.com',
    tipo: 'prestador',
    bio: 'Atendimento de emergência 24 horas. Residencial e Automotivo.',
    descricao_servico: 'Abertura de carros, casas, troca de segredos, cópias de chaves codificadas.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Centro',
    nota_media: 4.9,
    premium: true,
    servicos_oferecidos: ['Chaveiro', 'Fechaduras'],
    foto_url: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Abertura de Porta' }, preco_min: 100, preco_max: 200 }] as any
  },
  {
    id: 'mock-chaveiro-2',
    auth_id: 'mock-auth-chaveiro-2',
    nome: 'Socorro das Chaves',
    email: 'socorro.chaves@teste.com',
    tipo: 'prestador',
    bio: 'Cópias e aberturas. Preço justo.',
    descricao_servico: 'Cópia de chaves simples e tetra. Abertura de cadeados.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'São Cristóvão',
    nota_media: 4.6,
    premium: false,
    servicos_oferecidos: ['Chaveiro'],
    foto_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Cópia Simples' }, preco_min: 10, preco_max: 50 }] as any
  },

  // COZINHA
  {
    id: 'mock-cozinha-1',
    auth_id: 'mock-auth-cozinha-1',
    nome: 'Chef Helena',
    email: 'helena.chef@teste.com',
    tipo: 'prestador',
    bio: 'Personal Chef para jantares e eventos intimistas. Alta gastronomia.',
    descricao_servico: 'Jantares românticos, almoços de família, consultoria de cardápio.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Jardim Curitiba',
    nota_media: 5.0,
    premium: true,
    servicos_oferecidos: ['Cozinha', 'Chef', 'Gastronomia'],
    foto_url: 'https://images.unsplash.com/photo-1583336137498-afdf44ae98b6?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Jantar Completo' }, preco_min: 300, preco_max: 1200 }] as any
  },
  {
    id: 'mock-cozinha-2',
    auth_id: 'mock-auth-cozinha-2',
    nome: 'Bolos da Maria',
    email: 'maria.bolos@teste.com',
    tipo: 'prestador',
    bio: 'Bolos e doces para festas. Salgadinhos por encomenda.',
    descricao_servico: 'Kits para festa, bolos decorados, docinhos.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Violetas',
    nota_media: 4.8,
    premium: false,
    servicos_oferecidos: ['Cozinha', 'Confeitaria'],
    foto_url: 'https://images.unsplash.com/photo-1556910103-1c02745a30bf?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Bolo kg' }, preco_min: 60, preco_max: 120 }] as any
  },

  // TECNOLOGIA
  {
    id: 'mock-ti-1',
    auth_id: 'mock-auth-ti-1',
    nome: 'Lucas Tech Soluções',
    email: 'lucas.ti@teste.com',
    tipo: 'prestador',
    bio: 'Assistência técnica de computadores e notebooks. Redes e Wi-Fi.',
    descricao_servico: 'Formatação, remoção de vírus, upgrade de SSD, configuração de roteadores.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Centro',
    nota_media: 4.8,
    premium: true,
    servicos_oferecidos: ['Serviços de TI', 'Informática', 'Computador', 'Tecnologia'],
    foto_url: 'https://images.unsplash.com/photo-1504703395950-b89145154253?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Formatação' }, preco_min: 80, preco_max: 150 }] as any
  },
  {
    id: 'mock-ti-2',
    auth_id: 'mock-auth-ti-2',
    nome: 'Smart Cell Reparos',
    email: 'smartcell@teste.com',
    tipo: 'prestador',
    bio: 'Conserto de celulares e tablets. Troca de tela e bateria.',
    descricao_servico: 'Troca de display, conector de carga, banho químico.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Setor Comercial',
    nota_media: 4.6,
    premium: false,
    servicos_oferecidos: ['Serviços de TI', 'Celular', 'Tecnologia'],
    foto_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Troca de Tela' }, preco_min: 150, preco_max: 800 }] as any
  },

  // CUIDADOS
  {
    id: 'mock-cuidados-1',
    auth_id: 'mock-auth-cuidados-1',
    nome: 'Enfermeira Sandra',
    email: 'sandra.enf@teste.com',
    tipo: 'prestador',
    bio: 'Cuidadora de idosos e técnica de enfermagem. Experiência com acamados.',
    descricao_servico: 'Acompanhamento hospitalar, administração de medicamentos, curativos.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Jardim Jacarandás',
    nota_media: 5.0,
    premium: true,
    servicos_oferecidos: ['Cuidador(a) de idosos', 'Cuidados', 'Enfermagem'],
    foto_url: 'https://images.unsplash.com/photo-1554151228-14d9def656ec?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Plantão 12h' }, preco_min: 150, preco_max: 300 }] as any
  },
  {
    id: 'mock-cuidados-2',
    auth_id: 'mock-auth-cuidados-2',
    nome: 'Tia Ju Babá',
    email: 'ju.baba@teste.com',
    tipo: 'prestador',
    bio: 'Babá folguista e noturna. Amo crianças!',
    descricao_servico: 'Cuidados com bebês e crianças, brincadeiras educativas.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Residencial Florença',
    nota_media: 4.9,
    premium: false,
    servicos_oferecidos: ['Babá', 'Cuidados', 'Infantil'],
    foto_url: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Hora Babá' }, preco_min: 25, preco_max: 50 }] as any
  },
  {
    id: 'mock-cuidados-3',
    auth_id: 'mock-auth-cuidados-3',
    nome: 'Pet Sitter Carol',
    email: 'carol.pets@teste.com',
    tipo: 'prestador',
    bio: 'Cuido do seu pet quando você viaja. Passeios e visitas.',
    descricao_servico: 'Dog walking, visita domiciliar para gatos, alimentação.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Jardim Europa',
    nota_media: 4.8,
    premium: true,
    servicos_oferecidos: ['Pet Care', 'Cuidados', 'Animais'],
    foto_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Passeio' }, preco_min: 30, preco_max: 60 }] as any
  },

  // REFRIGERAÇÃO
  {
    id: 'mock-refri-1',
    auth_id: 'mock-auth-refri-1',
    nome: 'Ricardo Climatização',
    email: 'ricardo.clima@teste.com',
    tipo: 'prestador',
    bio: 'Especialista em ar condicionado Split e Inverter.',
    descricao_servico: 'Instalação, limpeza química, manutenção preventiva e corretiva.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Vila Popular',
    nota_media: 4.7,
    premium: true,
    servicos_oferecidos: ['Refrigeração', 'Ar Condicionado', 'Climatização'],
    foto_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Limpeza de Ar' }, preco_min: 150, preco_max: 250 }] as any
  },

  // MECÂNICO
  {
    id: 'mock-mecanico-1',
    auth_id: 'mock-auth-mecanico-1',
    nome: 'Oficina do Tiago',
    email: 'tiago.mecanico@teste.com',
    tipo: 'prestador',
    bio: 'Mecânica geral multimarcas. Injeção eletrônica e suspensão.',
    descricao_servico: 'Revisão geral, troca de óleo, freios, diagnóstico computadorizado.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Setor Industrial Norte',
    nota_media: 4.8,
    premium: true,
    servicos_oferecidos: ['Mecânico', 'Automotivo', 'Carro', 'Mecanico'],
    foto_url: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Mão de Obra' }, preco_min: 100, preco_max: 5000 }] as any
  },
  {
    id: 'mock-mecanico-2',
    auth_id: 'mock-auth-mecanico-2',
    nome: 'Borracharia do Zé',
    email: 'ze.borracha@teste.com',
    tipo: 'prestador',
    bio: 'Borracharia e socorro 24h.',
    descricao_servico: 'Conserto de pneus, vulcanização, troca de pneus.',
    endereco_cidade: 'Sinop, Mato Grosso',
    endereco_bairro: 'Av. das Acácias',
    nota_media: 4.5,
    premium: false,
    servicos_oferecidos: ['Mecânico', 'Borracharia'],
    foto_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&h=200&fit=crop&crop=face',
    criado_em: new Date().toISOString(),
    prestador_servicos: [{ servico: { nome: 'Conserto Pneu' }, preco_min: 30, preco_max: 80 }] as any
  }
];

// Duplicate some users to reach ~40 users for testing pagination/load more
export const MOCK_PRESTADORES: UserProfile[] = [
  ...basePrestadores,
  ...basePrestadores.map(p => ({
    ...p,
    id: p.id + '-copy',
    auth_id: p.auth_id + '-copy',
    nome: p.nome + ' (Filial)',
    endereco_cidade: 'Sinop, Mato Grosso', // Explicitly set city for copies
    nota_media: Math.max(3.5, p.nota_media! - 0.2), // Slightly different rating
    premium: !p.premium // Flip premium status for variety
  }))
];
